<?php
/** @var Mirasvit_Rma_Block_Adminhtml_Rma_Edit_Form $this */
$rma = $this->getRma();
$fieldForm = $this->getFieldForm();
$refundResolutionId = Mage::helper('rma')->getResolutionByCode('refund')->getId();
$exchangeResolutionId = Mage::helper('rma')->getResolutionByCode('exchange')->getId();
$isCreditEnabled = $this->getIsCreditEnabled();
?>

<script type="text/javascript">
    function isNumeric(obj) {
        return !jQuery.isArray( obj ) && (obj - parseFloat( obj ) + 1) >= 0;
    }

    function checkQtyOrdered(currentQty) {
        var ordered = parseInt($(currentQty.name.substring(0, 8) + '[qtyAvailable]').innerHTML.trim());
        var defaultQty = 0;
        if($('rma_id').value != '') {
         ordered += parseInt($(currentQty.name.substring(0, 8) + '[rma_item_qty]').value);
         defaultQty = ordered;
        }
        if(isNumeric(currentQty.value) && isNumeric(ordered)) {
            if(currentQty.value > ordered) {
                currentQty.value = defaultQty;
                alert("<?php echo $this->__('You can not return more, than available. Please, try again.') ?>");
            }
        }
    }
</script>

<form id="edit_form" action="<?php echo $this->getUrl('*/*/save') ?>" method="post" enctype="multipart/form-data">
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>"/>
    <input name='rma_id' id='rma_id' value='<?php echo $rma->getId() ?>' type='hidden'>
    <input name='order_id' value='<?php echo $rma->getOrderId() ?>' type='hidden'>

    <div class="entry-edit">

        <?php if ($fieldForm): ?>
            <div class="box-left">
                <div class="entry-edit">
                    <?php echo $this->getGeneralInfoForm()->toHtml() ?>
                </div>
            </div>
            <div class="box-right">
                <div class="entry-edit">
                    <?php echo $fieldForm->toHtml() ?>
                </div>
            </div>

            <div class="clear"></div>
        <?php else: ?>
            <?php echo $this->getGeneralInfoForm()->toHtml() ?>
        <?php endif; ?>

        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="fieldset-legend "><?php echo $this->__('Items') ?></h4>
            </div>
            <div class="fieldset">
                <div id="rma_item_edit_grid">
                    <div class="grid">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="data" id="rma_item_edit_grid_table">
                                <thead>
                                <tr class="headings">
                                    <th class="no-link"><span
                                            class="nobr"><?php echo $this->__('Product Name') ?></span></th>
                                    <th class="no-link"><span class="nobr">SKU</span></th>
                                    <th class="no-link"><span class="nobr"><?php echo $this->__('Stock Qty') ?></span>
                                    </th>
                                    <th class="no-link"><span class="nobr"><?php echo $this->__('Ordered Qty') ?></span>
                                    </th>
                                    <th class="no-link"><span class="nobr"><?php echo $this->__('Available Qty') ?></span>
                                    </th>
                                    <th class="no-link"><span
                                            class="nobr"><?php echo $this->__('Qty to Return') ?></span></th>
                                    <th class="no-link"><span
                                            class="nobr"><?php echo $this->__('Reason to Return') ?></span></th>
                                    <th class="no-link"><span
                                            class="nobr"><?php echo $this->__('Item Condition') ?></span></th>
                                    <th class="no-link"><span class="nobr"><?php echo $this->__('Resolution') ?></span>
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                $i = 0;
                                foreach (Mage::helper('rma')->getRmaItems($rma) as $item):
                                    $i++;
                                    ?>
                                    <?php if ($item->getProductType() == 'bundle'): ?>
                                    <tr class="even">
                                        <td><?php echo Mage::helper('rma')->getOrderItemLabel($item) ?> <?php echo $this->__('(Bundled Product)') ?></td>
                                        <td><?php echo $item->getProductSku() ?></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <?php
                                    continue;
                                endif
                                    ?>
                                    <tr <?php echo $rma->getId() > 0 && $item->getQtyRequested() == 0 ? "style='display:none;' class='even hidden_items'" : "class='even'"?>>
                                        <td>
                                            <?php if ($item->getIsBundleItem()): ?> &nbsp;&nbsp;&nbsp; <?php endif;?>
                                            <?php echo Mage::helper('rma')->getOrderItemLabel($item)?></td>
                                        <td><?php echo $item->getProductSku() ?></td>
                                        <td><?php echo $item->getQtyStock()?></td>
                                        <td id="items[<?php echo $i ?>][qtyOrdered]"> <?php  echo $item->getQtyOrdered() ?> </td>
                                        <td id="items[<?php echo $i ?>][qtyAvailable]"> <?php  echo $item->getQtyAvailable() ?> </td>
                                        <td>
                                            <input name='items[<?php echo $i ?>][item_id]'
                                                   value='<?php echo $item->getId()?>' type='hidden'>
                                            <input name='items[<?php echo $i ?>][order_item_id]'
                                                   value='<?php echo $item->getOrderItemId()?>' type='hidden'>
                                            <input id='items[<?php echo $i ?>][rma_item_qty]'
                                                   value='<?php echo $item->getQtyRequested() ? $item->getQtyRequested() : 0?>' type='hidden'>

                                            <input name='items[<?php echo $i ?>][qty_requested]'
                                                   class="input-text required-entry"
                                                   value='<?php echo $item->getQtyRequested() ? $item->getQtyRequested() : 0?>'
                                                   onKeyUp="checkQtyOrdered(this)">
                                        </td>
                                        <td>
                                            <select name="items[<?php echo $i ?>][reason_id]">
                                                <option value=""><?php echo $this->__('--')?></option>
                                                <?php foreach ($this->getReasonCollection() as $reason): ?>
                                                    <option
                                                        value="<?php echo $reason->getId() ?>" <?php echo $reason->getId() == $item->getReasonId() ? 'selected' : '' ?>><?php echo $reason->getName() ?></option>
                                                <?php endforeach;?>
                                            </select>
                                        </td>
                                        <td>
                                            <select name="items[<?php echo $i ?>][condition_id]">
                                                <option value=""><?php echo $this->__('--')?></option>
                                                <?php foreach ($this->getConditionCollection() as $condition): ?>
                                                    <option
                                                        value="<?php echo $condition->getId() ?>" <?php echo $condition->getId() == $item->getConditionId() ? 'selected' : '' ?>><?php echo $condition->getName() ?></option>
                                                <?php endforeach;?>
                                            </select>
                                        </td>
                                        <td>
                                            <select name="items[<?php echo $i ?>][resolution_id]">
                                                <option value=""><?php echo $this->__('--')?></option>
                                                <?php foreach ($this->getResolutionCollection() as $resolution): ?>
                                                    <option
                                                        value="<?php echo $resolution->getId() ?>" <?php echo $resolution->getId() == $item->getResolutionId() ? 'selected' : '' ?>><?php echo $resolution->getName() ?></option>
                                                <?php endforeach;?>
                                            </select>


                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <?php if ($rma->getId() > 0) : ?>
                        <a href='#'
                           onclick="$$('tr.hidden_items').each(Element.show);$(this).hide(); return false"><?php echo $this->__('Show all order items') ?></a>
                    <?php endif ?>
                </div>
            </div>
        </div>


        <div class="box-left">
            <div class="entry-edit">
                <?php echo $this->getShippingAddressForm()->toHtml() ?>
            </div>
        </div>
        <?php if ($this->getExchangeNewAmount()): ?>
        <div class="box-right">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Exchange/Credit Balance') ?></h4>
                    <div class="form-buttons"></div>
                </div>
                <div class="fieldset " id="field_fieldset">
                    <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
                            <tbody>
                            <?php if ($this->getIsCreditEnabled()): ?>
                                <tr>
                                    <td class="label"><label><?php echo $this->__('Customer credit balance:')?></label></td>
                                    <td class="value">
                                        <b><?php echo Mage::helper('core')->currency($this->getCreditAmount(), true, false);?></b>
                                    </td>
                                </tr>
                            <?php endif; ?>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Total price of new products:')?></label></td>
                                <td class="value">
                                    <b><?php echo Mage::helper('core')->currency($this->getExchangeNewAmount(), true, false);?></b>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Total price of exchanged/credit products:')?></label></td>
                                <td class="value">
                                    <b><?php echo Mage::helper('core')->currency($this->getExchangeOldAmount(), true, false);?></b>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Price difference:')?></label></td>
                                <td class="value">
                                    <b><?php echo Mage::helper('core')->currency($this->getExchangeDiffAmount(), true, false);?></b>
                                </td>
                            </tr>
                            <?php if ($this->getExchangeDiffAmount() != 0 && $this->getIsCreditEnabled()): ?>
                                <tr>
                                    <td class="label"><label><?php echo $this->__('Resolution:')?></label></td>
                                    <td class="value">
                                        <select name="exchange_credit">
                                            <?php if ($this->getExchangeDiffAmount() > 0 && $this->getExchangeDiffAmount() < $this->getCreditAmount()): ?>
                                                <option value="0"><?php echo $this->__('Get %s from customer credit balance', Mage::helper('core')->currency($this->getExchangeDiffAmount(), true, false))?></option>
                                            <?php endif;
                                            if ($this->getExchangeDiffAmount() < 0): ?>
                                                <option value="1"><?php echo $this->__('Put %s to customer credit balance', Mage::helper('core')->currency(abs($this->getExchangeDiffAmount()), true, false))?></option>
                                            <?php endif; ?>
                                            <option value="3"><?php echo $this->__('Resolve manually')?></option>
                                        </select>
                                    </td>
                                </tr>
                            <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <div class="box-right">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Return Address') ?></h4>

                    <div class="form-buttons"></div>
                </div>
                <div class="fieldset ">
                    <div class="hor-scroll">
                        <?php echo $this->getReturnAddressHtml() ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>
        <?php if ($rma->getId()) : ?>
            <div class="box-left">
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-edit-form"><?php echo $this->__('RMA History') ?></h4>

                        <div class="form-buttons">
                            <?php if ($rma->getIsAdminRead()): ?>
                                <button onclick="window.location='<?php echo $this->getMarkUrl(false) ?>'" type="button">
                                    <span><span><span><?php echo Mage::helper('adminhtml')->__('Mark as unread'); ?></span></span></span>
                                </button>
                            <?php else: ?>
                                <button onclick="window.location='<?php echo $this->getMarkUrl(true) ?>'" type="button">
                                    <span><span><span><?php echo Mage::helper('adminhtml')->__('Mark as read'); ?></span></span></span>
                                </button>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="fieldset">
                        <?php echo $this->getHistoryHtml() ?>
                    </div>
                </div>
            </div>
            <div class="box-right">
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Add Message') ?></h4>

                        <div class="form-buttons"></div>
                    </div>
                    <div class="fieldset " id="edit_fieldset">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list" style="width:100%">
                                <tbody>
                                <tr>
                                    <td class="value">
								<span class="field-row">
									<label for="reply_type"><?php echo $this->__('Message Type') ?></label>
									<select id="reply_type" name="reply_type" class=" select">
                                        <option value="public"
                                                selected="selected"><?php echo $this->__('Message to Customer') ?></option>
                                        <option value="internal"><?php echo $this->__('Internal Note') ?></option>
                                    </select>
									<div id="rma_reply_note"></div>
								</span>
                                        <?php echo $this->getTemplateForm()->toHtml() ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="value">
                                        <textarea id="reply" name="reply" rows="2" cols="30" class=" textarea"
                                                  style="width:92%"></textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="value">
                                        <input id="attachment" name="attachment[]" value="" class="multi" type="file"/>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        <?php endif; ?>
</form>
