<?php
/**
 * @var $this AAIT_Payexinvoice_Block_Adminhtml_Sales_Order_Create_Totals_Fee
 */
?>
<!-- Start Payexinvoice Payment Fee -->
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php $this->helper('factoring')->__('Payment fee'); ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('payexinvoice')->formatPrice($this->getPaymentFee()) ?>
    </td>
</tr>
<!-- End Payexinvoice Payment Fee -->
