<br/>
<br/>
<div class="grid12-4 gsp-flow">
    <!--<div class="cover"></div>-->
    <div class="feature feature-icon-hover"><span class="left ic ic-lg ic-anchor ib"></span>
        <h3>Popul&auml;ra produkter</h3>
        <p>H&auml;r finner du de mest k&ouml;pta och popul&auml;ra produkterna. H&auml;r kan du hitta allt fr&aring;n en
            LCD-sk&auml;rm
            till ett snyggt iPad skal.</p>
        <a href="<?php echo Mage::getUrl() . 'populara-produkter/' ?>" class="go">L&auml;s mer</a>
    </div>
</div>
<div class="grid12-4">
    <div class="feature feature-icon-hover"><span class="left ic ic-lg ic-gift ib"></span>
        <h3>Presenttips</h3>
        <p>Letar du efter en present till pappa och lillebror? H&auml;r hittar du produkter som vi tycker man kan ge
            bort i present
            till n&auml;ra och k&auml;ra</p>
        <a href="<?php echo Mage::getUrl() . 'presenttips/' ?>" class="go">L&auml;s mer</a>
    </div>
</div>
<div class="grid12-4">
    <div class="feature feature-icon-hover"><span class="left ic ic-lg ic-edit2 ib"></span>
        <h3>Outlet</h3>
        <p>H&auml;r hittar du produkter som vi rear ut, troligen kommer vi inte ta in produkterna igen s&aring; passa p&aring;!</p>
        <a href="<?php echo Mage::getUrl() . 'outlet/' ?>" class="go">L&auml;s mer</a>
    </div>
</div>