<?php
/**
 * @category    Evalent Modules
 * @package     Evalent_Admin
 * @author      eValent Group AB
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Mage::helper('adminhtml')->__('Log into Magento Admin Page'); ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('reset.css'); ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('boxes.css'); ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/login.css') ?>" media="all" />
    <link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico'); ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico'); ?>" type="image/x-icon" />

    <script type="text/javascript" src="<?php echo $this->getJsUrl(); ?>index.php/x.js?f=prototype/prototype.js,prototype/validation.js,mage/adminhtml/events.js,mage/adminhtml/form.js,scriptaculous/effects.js"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/captcha.js') ?>"></script>
</head>
<body id="page-login">
    <form method="post" action="" id="loginForm">
        <fieldset class="login-form">
            <input name="form_key" type="hidden" value="<?php echo $this->getFormKey(); ?>" />
            <h2><?php echo Mage::helper('adminhtml')->__('Forgot your user name or password?'); ?></h2>
            <div id="messages">
                <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
            </div>
            <div class="input-box forgot-password"><label for="email"><?php echo Mage::helper('adminhtml')->__('Email Address:'); ?></label><br />
                <input type="text" id="email" name="email" value="" class="required-entry input-text forgot-password validate-email" style="width:474px;" />
            </div>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
            <div class="form-buttons">
                <a class="left" href="<?php echo $this->getUrl('adminhtml', array('_nosecret' => true)); ?>">&laquo; <?php echo Mage::helper('adminhtml')->__('Back to Login'); ?></a>
                <button class="forgot-password" onclick="loginForm.submit()" type="button"><span><span><span><?php echo Mage::helper('adminhtml')->__('Retrieve Password'); ?></span></span></span></button>
            </div>
        </fieldset>
    </form>
    <script type="text/javascript">
         var loginForm = new varienForm('loginForm');
    </script>
    <p class="legal"><?php echo Mage::helper('adminhtml')->__('Magento is a trademark of Magento Inc. Copyright &copy; %s Magento Inc.', date('Y')); ?></p>
</body>
</html>

