<?php
/**
 * @category    Evalent Modules
 * @package     Evalent_Admin
 * @author      eValent Group AB
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Mage::helper('adminhtml')->__('Log into Magento Admin') ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('reset.css') ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('boxes.css') ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/login.css') ?>" media="all" />
    <link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />

    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/prototype.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/validation.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('scriptaculous/effects.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/adminhtml/form.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/captcha.js') ?>"></script>
</head>
<body id="page-login" onload="document.forms.loginForm.username.focus();">
    <form method="post" action="" id="loginForm">
        <div class="login-form">
            <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
            <!--h2><?php //echo Mage::helper('adminhtml')->__('Magento Admin login') ?></h2-->
            <div id="messages">
                <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
            </div>
            <div class="input-box input-left"><label for="username"><?php echo Mage::helper('adminhtml')->__('User Name:') ?></label><br/>
                <input type="text" id="username" name="login[username]" value="" class="required-entry input-text" /></div>
            <div class="input-box input-right"><label for="login"><?php echo Mage::helper('adminhtml')->__('Password:') ?></label><br />
                <input type="password" id="login" name="login[password]" class="required-entry input-text" value="" /></div>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
            <div class="form-buttons">
                <a class="left" href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/index/forgotpassword', array('_nosecret' => true)) ?>"><?php echo Mage::helper('adminhtml')->__('Forgot your password?') ?></a>
                <input type="submit" class="form-button" value="<?php echo Mage::helper('adminhtml')->__('Login') ?>" title="<?php echo Mage::helper('adminhtml')->__('Login') ?>" />
            </div>
            <div class="login-footer">
                <a href="http://www.evalent.com" target="_blank">eValent Group AB</a><span class="separator">|</span><a href="http://www.evalent.com/#contact" target="-blank"><?php echo $this->__('Contact Us') ?></a>
            </div>
        </div>
        <p class="legal"><?php echo Mage::helper('adminhtml')->__('Magento is a trademark of Magento Inc. Copyright &copy; %s Magento Inc.', date('Y')); ?></p>
    </form>
    <script type="text/javascript">
         var loginForm = new varienForm('loginForm');
    </script>
</body>
</html>

