<?php
/**
 * @category    Evalent Modules
 * @package     Evalent_Admin
 * @author      eValent Group AB
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo Mage::helper('adminhtml')->__('Reset a Password'); ?></title>
        <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('reset.css'); ?>" media="all" />
        <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('boxes.css'); ?>" media="all" />
        <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/login.css') ?>" media="all" />
        <link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico'); ?>" type="image/x-icon" />
        <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico'); ?>" type="image/x-icon" />

        <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>index.php/x.js?f=prototype/prototype.js,prototype/validation.js,mage/adminhtml/events.js,mage/adminhtml/form.js,scriptaculous/effects.js"></script>
    </head>
    <body id="page-login">
                <form method="post" action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $userId, 'token' => $resetPasswordLinkToken))); ?>" id="reset-password-form">
                    <fieldset class="login-form">
                        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey(); ?>" />
                        <h2><?php echo Mage::helper('adminhtml')->__('Reset a Password'); ?></h2>
                        <div id="messages">
                            <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
                        </div>
                        <div class="input-box f-left">
                            <label for="password"><em class="required">*</em> <?php echo $this->__('New Password'); ?></label>
                            <br />
                            <input type="password" class="input-text required-entry validate-admin-password" name="password" id="password" />
                        </div>
                        <div class="input-box f-right">
                            <label for="confirmation"><em class="required">*</em> <?php echo $this->__('Confirm New Password'); ?></label>
                            <br />
                            <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                        </div>
                        <div class="form-buttons">
                            <a class="left" href="<?php echo $this->getUrl('adminhtml', array('_nosecret' => true)) ?>">&laquo; <?php echo Mage::helper('adminhtml')->__('Back to Login'); ?></a>
                            <button type="submit" title="<?php echo Mage::helper('adminhtml')->__('Reset Password'); ?>" class="forgot-password"><span><span><span><?php echo Mage::helper('adminhtml')->__('Reset Password'); ?></span></span></span></button>
                        </div>
                    </fieldset>
                    <p class="legal"><?php echo Mage::helper('adminhtml')->__('Magento is a trademark of Magento Inc. Copyright &copy; %s Magento Inc.', date('Y')); ?></p>
                </form>
                <script type="text/javascript">
                    var resetPasswordForm = new varienForm('reset-password-form');
                </script>
    </body>
</html>
