<?php
/**
 * @category    Evalent Modules
 * @package     Evalent_Admin
 * @author      eValent Group AB
 */

/** @var $this Mage_Adminhtml_Block_Page_Header */
?>

<div class="header-top">
    <div class="logo">
       <a href="<?php echo $this->getHomeLink() ?>"><img src="<?php echo $this->getSkinUrl($this->__('images/logo-admin.png')) ?>" alt="<?php echo $this->__('Ecompartner') ?>" /></a>
    </div>
    <div class="info">
        <a href="http://www.evalent.com" target="_blank">eValent</a>
        <span class="separator">|</span>
        <a href="http://www.evalent.com/#contact" target="_blank"><?php echo $this->__('Contact Us') ?></a>
        <span class="separator">|</span>
        <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>" target="blank"><?php echo $this->__('To the Store ->') ?></a>
        <span style="padding: 0 15px;"></span>
        <span><?php echo $this->__('Logged in as: <strong>%s</strong>', $this->escapeHtml($this->getUser()->getUsername())) ?></span>
        <span class="separator">|</span>
        <span><?php echo $this->formatDate(null, 'short') ?></span>
        <span class="separator">|</span>
        <a href="<?php echo $this->getLogoutLink() ?>" class="link-logout"><?php echo $this->__('Log Out') ?></a>
    </div>
</div>
