<?php $quote = $this->getQuote() ?>
<div id="klarnacheckout-coupon-wrapper">
    <div class="step-two">
        <div class="klarnacheckout-fieldset">
            <div class="klarnacheckout-coupon-field hide">
                <div id="kco-coupon-info" style="display: none;"></div>
                <?php $_couponCode = $quote->getCouponCode(); ?>
                <h2>
                    <label for="kco_coupon_code"><?php echo $this->__('Use Coupon'); ?> <span>+</span></label>
                </h2>
                <input class="input-text" type="text" id="kco-coupon-code" value="<?php echo $_couponCode; ?>" <?php echo $_couponCode == '' ? '' : 'disabled="disabled"'; ?> />
                <button class="kco-action" type="button" data-action="couponCodeAdd" style="<?php echo $_couponCode == '' ? '' : 'display: none;'; ?>">
                    <?php echo $this->__('Use coupon'); ?>
                </button>
                <button id="kco-coupon-remove" class="kco-action" type="button" data-action="couponCodeRemove" style="<?php echo $_couponCode == '' ? 'display: none;':''; ?>">
                    <?php echo $this->__('Remove coupon'); ?>
                </button>
            </div>
        </div>

        <script type="text/javascript">
            //<![CDATA[

            var label = $$('.klarnacheckout-coupon-field')[0];
            //label.addClassName('hide');
            label.down('label').observe('click', toogleKcoDiscountBox);

            function toogleKcoDiscountBox(event) {
                var label = $$('.klarnacheckout-coupon-field')[0];

                label.toggleClassName('hide');
                if(label.hasClassName('hide')) label.down('label').innerHTML = '<?php echo $this->__('Use Coupon'); ?> <span>+</span>';
                else label.down('label').innerHTML = '<?php echo $this->__('Use Coupon'); ?> <span>-</span>';

            }


            //]]>
        </script>
    </div>
</div>