<?php $skipJS = true;
require('common.phtml'); ?>

<div class="fm-container">
    <div class="fm-header">
        <div class="fm-header-wrapper">
            <img class="navbar-brand" src="<?php echo $this->getSharedPath(); ?>frontend/images/logo.png"
                 alt="<?php echo $this->getMessage('Fyndiq logotype'); ?>">
        </div>
    </div>

    <div class="fm-content-wrapper">
        <div class="fm-update-message-container"></div>
        <div class="fm-panel">
            <div class="fm-panel-header"><?php echo $this->getMessage(
                    'Unfortunately, Fyndiq API is currently not available.'
                ) ?></div>
            <div class="fm-panel-body">
                <p>
                    <?php echo $this->getMessage(
                        'If this problem persists, please contact integration support, and attach the error message shown below.'
                    ) ?>
                </p>

                <p>
                    <?php echo $this->getMessage('Error message') ?>:
                    <strong><?php echo $this->data['message']; ?></strong>
                </p>
            </div>
        </div>
        <br class="clear" />
        <div class="fm-content-wrapper fm-footer muted text-right">
            <a href="<?php echo $this->getAdminPath("fyndiq/admin/check"); ?>"><?php echo $this->getMessage('Check module'); ?></a>
            <img class="fm-update-check" style="display:none" src="<?php echo $this->getSharedPath() ?>frontend/images/update-loader.gif" />
            <?php echo $this->getVersion(); ?>
        </div>
    </div>
</div>
