<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getFrontendPath(); ?>frontend/css/main.css" media="all">

<?php if (empty($skipJS)) { ?>
    <script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript">
        $.noConflict();
        var FmPaths = {
            module: '<?php echo $this->getAdminPath("fyndiq/service"); ?>',
            shared: '<?php echo $this->getSharedPath(); ?>',
            service: '<?php echo $this->getServicePath() ?>',
            url: '<?php echo str_replace('index.php/','',Mage::getBaseUrl()); ?>'
        };
        var extra_data = {'form_key': window.FORM_KEY};
        var messages = <?php echo json_encode($this->getMessages())?>;
        var fmRepositoryPath = '<?php echo $this->getRepositoryPath() ?>';
        var fmModuleVersion = '<?php echo $this->getModuleVersion() ?>';
        var fmDisableUpdateCheck = <?php echo $this->getDisableUpdateCheck() ?>;
    </script>
<?php } ?>
<style type="text/css">
    a i.menu-icon.comp {
        background-image: url('<?php echo $this->getSharedPath(); ?>frontend/images/icons/comp_red.png');
    }

    a.active i.menu-icon.comp, a:hover i.menu-icon.comp {
        background-image: url('<?php echo $this->getSharedPath(); ?>frontend/images/icons/comp_white.png');
    }

    a i.menu-icon.boxes {
        background-image: url('<?php echo $this->getSharedPath(); ?>frontend/images/icons/box_red.png');
    }

    a.active i.menu-icon.boxes, a:hover i.menu-icon.boxes {
        background-image: url('<?php echo $this->getSharedPath(); ?>frontend/images/icons/box_white.png');
    }

    a i.menu-icon.cog {
        background-image: url('<?php echo $this->getSharedPath(); ?>frontend/images/icons/cog_red.png');
    }

    a.active i.menu-icon.cog, a:hover i.menu-icon.cog {
        background-position: 0px -1px;
        background-image: url('<?php echo $this->getSharedPath(); ?>frontend/images/icons/cog_white.png');
    }
</style>
<?php if (empty($skipJS)) { ?>
    <?php require(MAGENTO_ROOT . '/fyndiq/shared/frontend/templates/js_templates.tpl'); ?>

    <script type="text/javascript" src="<?php echo $this->getSharedPath(); ?>frontend/js/handlebars-v1.1.2.js"></script>
    <script type="text/javascript" src="<?php echo $this->getSharedPath(); ?>frontend/js/FmGui.js"></script>
    <script type="text/javascript" src="<?php echo $this->getSharedPath(); ?>frontend/js/FmCtrl.js"></script>
    <script type="text/javascript" src="<?php echo $this->getSharedPath(); ?>frontend/js/FmUpdate.js"></script>
<?php } ?>


<div class="fm-switcher">
    <label for="store_switcher"><?php echo $this->__('Current Configuration Scope:') ?></label>
    <select id="store_switcher" class="system-config-store-switcher"
            onchange="location.href=this.options[this.selectedIndex].getAttribute('url')">
        <?php foreach ($this->getStoreSelectOptions() as $_value => $_option): ?>
        <?php if (isset($_option['is_group'])): ?>
        <?php if ($_option['is_close']): ?>
            </optgroup>
        <?php else: ?>
        <optgroup label="<?php echo $this->escapeHtml($_option['label']) ?>" style="<?php echo $_option['style'] ?>">
            <?php endif; ?>
            <?php continue ?>
            <?php endif; ?>
            <option value="<?php echo $this->escapeHtml($_value) ?>"
                    url="<?php echo $_option['url'] ?>" <?php echo $_option['selected'] ? 'selected="selected"' : '' ?>
                    style="<?php echo $_option['style'] ?>">
                <?php echo $this->escapeHtml($_option['label']) ?>
            </option>
            <?php endforeach ?>
    </select>
</div>
