<?php $skipJS = true;
require('common.phtml'); ?>

<div class="fm-container">
    <div class="fm-header">
        <div class="fm-header-wrapper">
            <img class="navbar-brand" src="<?php echo $this->getSharedPath(); ?>frontend/images/logo.png"
                 alt="<?php echo $this->getMessage('Fyndiq logotype'); ?>">
        </div>
    </div>

    <div class="fm-content-wrapper">
        <div class="fm-update-message-container"></div>
        <div class="fm-panel">
            <div class="fm-panel-header"><?php echo $this->getMessage('Setting up your Fyndiq Connection'); ?></div>
            <div class="fm-panel-body">
                <p>
                    <?php echo $this->getMessage(
                        'By authenticating you will create a permanent connection to your Fyndiq merchant account.'
                    ); ?><br/>
                    (<?php echo $this->getMessage(
                        'You will not have to authenticate again when coming here next time.'
                    ); ?>)
                </p>

                <p>
                    <?php echo $this->getMessage(
                        'If you see this page again, it means you typed in wrong credentials and need to type in correct token and username.'
                    ); ?>
                </p>
                <a class="fm-button green" type="submit" name="submit_show_settings"
                   href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>">
                    <?php echo $this->getMessage('Go to Settings'); ?>
                </a>
            </div>
        </div>
        <br class="clear" />
        <div class="fm-content-wrapper fm-footer muted text-right">
            <a href="<?php echo $this->getAdminPath("fyndiq/admin/check"); ?>"><?php echo $this->getMessage('Check module'); ?></a>
            <img class="fm-update-check" style="display:none" src="<?php echo $this->getSharedPath() ?>frontend/images/update-loader.gif" />
            <?php echo $this->getVersion(); ?>
        </div>
    </div>
</div>
