<?php require('common.phtml'); ?>

<script type="text/javascript" src="<?php echo $this->getSharedPath(); ?>frontend/js/order.js"></script>

<div class="fm-container">

    <div class="fm-header">
        <div class="fm-header-wrapper">
            <img class="navbar-brand" src="<?php echo $this->getSharedPath(); ?>frontend/images/logo.png"
                 alt="<?php echo $this->getMessage('Fyndiq logotype'); ?>">

            <div class="navbar-right">
                <a href="<?php echo $this->getAdminPath("fyndiq/admin/index"); ?>" class="btn btn-nav"><i
                        class="menu-icon comp"></i> <?php echo $this->getMessage('Export Products'); ?></a>
                <?php if ($this->ordersEnabled($this->getRequest()->getParam('store'))): ?>
                <a href="<?php echo $this->getAdminPath("fyndiq/admin/orderlist"); ?>" class="btn btn-nav"><i
                        class="menu-icon boxes"></i> <?php echo $this->getMessage('Imported Orders'); ?></a>
                <?php endif; ?>
                <a href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>"
                   class="btn btn-nav"><i class="menu-icon cog"></i> <?php echo $this->getMessage('Settings'); ?></a>
            </div>
        </div>
    </div>


    <div class="fm-content-wrapper">
        <div class="fm-update-message-container"></div>
        <div class="fm-orderlist-panel">
            <div class="fm-panel">
                <div class="fm-panel-header"><?php echo $this->getMessage('Imported Orders'); ?></div>
                <div class="fm-panel-body no-padding">
                    <form action="<?php echo $this->getServicePath() ?>" method="post" class="fm-form orders-form">
                        <input type="hidden" name="action" value="get_delivery_notes"/>
                        <input type="hidden" name="form_key"
                               value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

                        <div class="fm-order-list-container"></div>
                    </form>
                </div>
            </div>
        </div>

        <div class="fm-sidebar">
            <div class="fm-panel">
                <div class="fm-panel-header"><?php echo $this->getMessage('Manual Order Import'); ?></div>
                <div class="fm-panel-body">
                    <p><?php echo $this->getMessage(
                            'By clicking this button, you can import all orders from Fyndiq into the local webshop.'
                        ); ?></p>

                    <div id="fm-order-import-date">
                        <?php
                        $currentDate = $this->getLastUpdatedDate($this->getRequest()->getParam('store'));
                        if ($currentDate != false) {
                            ?>
                            <div class="lastupdated">
                                <img src="<?php echo $this->getSharedPath(); ?>frontend/images/icons/refresh.png"/>
                                <span class="last-header"><?php echo $this->getMessage('Latest Import'); ?></span>
                                <?php
                                $current = strtotime(date("Y-m-d"));
                                $date = strtotime(date("Y-m-d", strtotime($currentDate)));

                                $dateDiff = $date - $current;
                                $difference = floor($dateDiff / (60 * 60 * 24));
                                if ($difference == 0) {
                                    echo $this->getMessage('Today') . ' <span class="shadow">(' . date(
                                            "G:i:s",
                                            strtotime($currentDate)
                                        ) . ')</span>';
                                } else {
                                    echo date("Y-m-d G:i:s", strtotime($currentDate));
                                }
                                ?>
                            </div>
                        <?php
                        }
                        ?>
                    </div>
                    <a class="fm-button green" id="fm-import-orders"><?php echo $this->getMessage(
                            'Import Orders'
                        ); ?></a>
                </div>
            </div>
        </div>
        <br class="clear" />
        <div class="fm-content-wrapper fm-footer muted text-right">
            <a href="<?php echo $this->getAdminPath("fyndiq/admin/check"); ?>"><?php echo $this->getMessage('Check module'); ?></a>
            <img class="fm-update-check" style="display:none" src="<?php echo $this->getSharedPath() ?>frontend/images/update-loader.gif" />
            <?php echo $this->getVersion(); ?>
        </div>
    </div>
