<?php
/**
 * Dibs A/S
 * Dibs Payment Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Payments & Gateways Extensions
 * @package    Dibspw_DibspwModule
 * @author     Dibs A/S
 * @copyright  Copyright (c) 2010 Dibs A/S. (http://www.dibs.dk/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$paymate = Mage::getModel('dibspw/Dibspw');
$_code=$this->getMethodCode();
$sHTML = '<fieldset class="form-list">
          <ul id="payment_form_'.$_code. '" style="display:none">
          <li>' . $this->__('DIBSPW_LABEL_1');
$aLogoArray = array();
explode(',', $paymate->getConfigData('dibspwlogos'));
$sTrusted = '';
$sCards = '';
$iCards = 1;
$iTrusted = 1;
foreach($aLogoArray as $item) {
    $mSecured = (boolean)preg_match("/^(DIBS|PCI|.*_SECURE.*)$/s", $item);
    if($mSecured === TRUE){
        $sTrusted .= $paymate->cms_get_imgHtml($item) . "&nbsp;&nbsp;";
        if($iTrusted%12 == 0) $sTrusted .= "<br />";
        $iTrusted++;
    }
    else {
        $sCards .= $paymate->cms_get_imgHtml($item) . "&nbsp;&nbsp;";
        if($iCards%12 == 0) $sCards .= "<br />";
        $iCards++;
    }
}

if(!empty($sTrusted)) $sHTML .= '<br /><br />' . $sTrusted;
if(!empty($sCards)) $sHTML .= '<br /><br />' . $this->__('DIBSPW_LABEL_2') . '<br />' . $sCards;

$sHTML .= $paymate->getConfigData('cardlogos');
$sHTML .= $paymate->getConfigData('netbanklogos');
$html = $paymate->getConfigData('invoicelogos');
$html = preg_replace('/class="dibs_brand_assets"/', "class=\"dibs_brand_assets\" id=\"dibs_invoice_container\"", $html);  
$scriptPattern = '/(<script.*"(.*)".*"(.*)".*"(.*)".*>)/';
 preg_match($scriptPattern, $html, $matches);
 if( isset($matches[0]) && $matches[0] ) {
 $src = $matches[2];
 $data_dibs_terms_filename = $matches[3];
 $data_terms_container_id = $matches[4];
 $replacement = "<script type=\"text/javascript\">
                    var js = document.createElement(\"script\"); js.src = '". $src ."';
                    js.setAttribute('data-terms-container-id','".$data_terms_container_id."');
                    js.setAttribute('data-dibs-terms-filename','".$data_dibs_terms_filename."');
                    var container = document.getElementById(\"dibs_invoice_container\");
                    container.appendChild(js);
                </script>";
 $html = preg_replace('/< *script.*><\/script>/', $replacement, $html);
 }
 $sHTML .= $html;
 $sHTML .= '</li></ul></fieldset>';
 echo $sHTML;
?>